#!/usr/bin/env bash
#
# @file Install brew formulae.

set -e

readonly BASEDIR="$(dirname "$0")"
source "${BASEDIR}/../shell/utilities.sh"

#
# Install forumulae used for system administration on a Mac system.
#
# usage: install_core_formulae
#
install_core_formulae() {
  brew tap homebrew/services 

  brew install mas
  brew install encfs

  brew install bash bash-completion@2
  brew install tmux

  brew install coreutils
  brew install curl
  brew install grep
  brew install rsync
  brew install wget
  brew install htop --with-ncurses

  brew install ack
  brew install ripgrep
  brew install tree
}

#
# Install formulae of choise used during Web Development.
#
# usage: install_web_formulae
#
install_web_formulae() {
  brew tap homebrew/php

  brew install neovim
  brew install python3

  brew install git

  brew install --HEAD universal-ctags/universal-ctags/universal-ctags

  brew install httpd
  brew install yarn --without-node
  brew install tidy-html5

  brew install php71 --with-httpd --with-homebrew-curl
  brew install php71-xdebug
  brew install composer
  brew install adminer

  brew install shellcheck
}

#
# Install shell utilities using Homebrew the missing package manager for macOS.
#
# usage: install [<profile>]
#
install() {
  if ! command -v brew >/dev/null 2>&1; then
    dot::exit "Cannot find homwbrew command"
  fi

  local profile="${1:-full}"
  
  case "${profile}" in
    full)
      install_core_formulae
      install_web_formulae
      ;;
    *)
      install_core_formulae
      ;;
  esac 
}

install "$@"
