#!/usr/bin/env bash
#
# @file Install macOS applications using homebrew.

set -e

readonly SCRIPT_DIR="$(dirname "$0")"
readonly DOTFILES="${DOTFILES:-$(dirname "$SCRIPT_DIR")}"

source "${DOTFILES}/shell/utilities.sh"

if ! dot::command_exists "brew"; then
  dot::exit "Cannot find homebrew command"
fi

dot::info "Installing cask formulae …"

brew cask install alfred
brew cask install bartender
brew cask install 1password
brew cask install daisydisk
brew cask install tad
brew cask install the-unarchiver

brew cask install firefox
brew cask install google-chrome

brew cask install spotify

brew cask install imagealpha
brew cask install imageoptim

brew cask install fira-code
brew cask install source-code-pro

brew cask install qlcolorcode
brew cask install qlmarkdown
brew cask install qlstephen
