#!/usr/bin/env bash
#
# @file Install latest npm version and default packages.

set -e

__install() {
  npm install --global --production npm@latest

  npm install --global --production yo
  npm install --global --production eslint

  if [[ -n "$DOTFILES" ]]; then
    while read -r package; do
      if [[ "$package" != "yo" ]] && [[ "$package" != "eslint" ]]; then
        nvm install --global --production "$package"
      fi
    done < "${DOTFILES}/misc/default-packages"
  fi
}

__install

# vim:foldmethod=marker:foldlevel=2
