#!/usr/bin/env bash
#
# @file Install latest npm version and default packages.

set -e

readonly BASEDIR="$(dirname "$0")"
source "${BASEDIR}/../shell/utilities.sh"

__install() {
  if ! command -v npm >/dev/null 2>&1; then
    dot::exit "Cannot find npm command"
  fi

  npm install --global --production npm@latest

  npm install --global --production yo
  npm install --global --production eslint

  if [[ -n "$DOTFILES" ]]; then
    while read -r package; do
      if [[ "$package" != "yo" ]] && [[ "$package" != "eslint" ]]; then
        npm install --global --production "$package"
      fi
    done < "${DOTFILES}/misc/default-packages"
  fi
}

__install

# vim:foldmethod=marker:foldlevel=2
