#!/usr/bin/env bash
#
# @file Install Node Version Manager.

set -e

readonly BASEDIR="$(dirname "$0")"
source "${BASEDIR}/../shell/utilities.sh"

#
# Download and install the Node Version Manager and load the latest
# version of node.js
#
# usage: install [<path>] [<version>]
#
install() {
  local path="${1:-$HOME/.local/share/nvm}"
  local version="${2:-latest}"

  git clone "https://github.com/creationix/nvm.git" "$path" || {
    dot::exit "Cannot checkout nvm repository"
  }

  cd "$path"

  if [[ "$version" = "latest" ]]; then
    version=$(git describe --abbrev=0 --tags --match "v[0-9]*" origin)
  fi

  git checkout "$version"
  source "$path/nvm.sh"

  nvm install --lts
}

install "$@"
