#!/usr/bin/env bash
#
# @file Install Node Version Manager.

set -e

__install() {
  local path="${1:-$HOME/.config/nvm}"
  local version="${2:-latest}"

  git clone "https://github.com/creationix/nvm.git" "$path" || {
    echo -e "\033[0;31m==> Cannot checkout nvm repository\033[0;m" >&2
    exit 1
  }

  cd "$path"

  if [[ "$version" = "latest" ]]; then
    version=$(git describe --abbrev=0 --tags --match "v[0-9]*" origin)
  fi

  git checkout "$version"
  source "$path/nvm.sh"

  nvm install node
  nvm use node
  nvm alias default node
}

__install "$@"
