#!/usr/bin/env bash
#
# @file Install latest pip version and default packages.

set -e

readonly SCRIPT_DIR="$(dirname "$0")"
readonly DOTFILES="${DOTFILES:-$(dirname "$SCRIPT_DIR")}"

source "${DOTFILES}/shell/utilities.sh"

#
# Get the value of a phpcs configuration variable.
#
# usage: get_phpcs_config <name>
#
get_phpcs_config() {
  phpcs --config-show \
    | grep "$1" \
    | cut -d: -f2 \
    | sed -e 's/^[[:space:]]*//g'
}

#
# Customize the default configuration used when running php code sniffer.
#
# usage: confige_phpcs
#
configure_phpcs() {
  phpcs --config-set default_standard PSR2
  phpcs --config-set show_progress 1
  phpcs --config-set colors 1
  phpcs --config-set report_width auto
}

#
# Install the WordPress coding standards.
#
# usage: install_wpc
#
install_wpc() {
  local directory="${XDG_DATA_HOME:-$HOME/.local/share}/phpcs/Standards/WordPress"

  if [[ -d "${directory}" ]]; then
    return 0
  fi

  local paths
  paths="$(get_phpcs_config "installed_paths")"

  git clone -b master https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git "${directory}"
  phpcs --config-set installed_paths "${paths},${directory}"
}

#
# Configure php utilities on the current system.
#
main() {
  if dot::command_exists "phpcs"; then
    if dot::confirm "Do you want to customize the default settings used by php code sniffer?"; then
      confige_phpcs
    fi

    if dot::confirm "Do you want to install the WordPress Coding Standards?"; then
      install_wpc
    fi
  fi
}

main "$@"
