#!/usr/bin/env bash
#
# @file Install latest pip version and default packages.

set -e

readonly SCRIPT_DIR="$(dirname "$0")"
readonly DOTFILES="${DOTFILES:-$(dirname "$SCRIPT_DIR")}"

source "${DOTFILES}/shell/utilities.sh"


if ! dot::command_exists "pip3"; then
  dot::exit "Cannot find pip3 command"
fi

dot::info "Updating pip …"
pip3 install --upgrade pip

dot::info "Installing python packages …"

while read -r package; do
  pip3 install --upgrade "$package"
done < "${DOTFILES}/misc/default-python-packages"
