#!/usr/bin/env bash
#
# @file Install default gems.

set -e

readonly BASEDIR="$(dirname "$0")"
source "${BASEDIR}/../shell/utilities.sh"

#
# Downlaod and install global ruby gems.
#
# usage: install
# 
install() {
  if ! command -v rvm >/dev/null 2>&1; then
    dot::exit "Cannot find rvm command"
  fi

  if [[ -n "${DOTFILES}" ]]; then
    while read -r name; do
      rvm @global do gem install "$name"
    done < "${DOTFILES}/misc/default-gems"
  fi
}

install "$@"
