#!/usr/bin/env bash
#
# @file Install latest ruby version and default gems.

set -e

__install() {
  if ! command -v rvm >/dev/null 2>&1; then
    echo -e "\033[0;31m==> Cannot find rvm command\033[0;m" >&2
    exit 1
  fi

  # (1) Ruby ----------------------------------------------------------- {{{1

  rvm install ruby
  rvm use ruby

  # (2) Default Gems --------------------------------------------------- {{{1

  if [[ -n "${DOTFILES}" ]]; then
    while read -r name; do
      rvm @global do gem install "$name"
    done < "${DOTFILES}/misc/default-gems"
  fi
}

__install

# vim:foldmethod=marker:foldlevel=2
