#!/usr/bin/env bash
#
# @file Install default gems.

set -e

readonly SCRIPT_DIR="$(dirname "$0")"
readonly DOTFILES="${DOTFILES:-$(dirname "$SCRIPT_DIR")}"

source "${DOTFILES}/shell/utilities.sh"

if ! dot::command_exists "rvm"; then
  dot::exit "Cannot find rvm command"
fi

dot::info "Installing global gems …"

while read -r name; do
  rvm @global do gem install "$name"
done < "${DOTFILES}/misc/default-gems"
