#!/usr/bin/env bash
#
# @file Install Ruby Version Manager.

set -e

__install() {
  local path="${1:-$HOME/.config/rvm}"

  curl -sSL https://get.rvm.io \
    | bash -s -- --path "$path" --ignore-dotfiles --ruby
}

__install "$@"
