#!/usr/bin/env bash
#
# @file Install Ruby Version Manager.

set -e

readonly SCRIPT_DIR="$(dirname "$0")"
readonly DOTFILES="${DOTFILES:-$(dirname "$SCRIPT_DIR")}"

source "${DOTFILES}/shell/utilities.sh"

readonly RVM_DIR"${1:-$HOME/.local/share/rvm}"

dot::info "Installing rvm …"

curl -sSL "https://get.rvm.io" \
  | bash -s -- --path "$RVM_DIR" --ignore-dotfiles --ruby
