#!/usr/bin/env bash
#
# @file Create symlinks to dotfiles.

set -e

readonly BASEDIR="$(dirname "$0")"
source "${BASEDIR}/../shell/utilities.sh"

__symlinks() {
  local profile="${1:-full}"
}

__symlinks "$@"

# vim:foldmethod=marker:foldlevel=2
