#!/usr/bin/env bash
#
# @file Install tmux plugin manager.

set -e

readonly SCRIPT_DIR="$(dirname "$0")"
readonly DOTFILES="${DOTFILES:-$(dirname "$SCRIPT_DIR")}"

source "${DOTFILES}/shell/utilities.sh"


readonly TMUX_PLUGIN_DIR="${TMUX_PLUGIN_MANAGER_PATH:-$HOME/.local/share/tmux/plugins}"
readonly TPM_DIR="${TMUX_PLUGIN_DIR}/tpm"

dot::info "Installing tmux plugin manager …"

git clone "https://github.com/tmux-plugins/tpm" "$TPM_DIR" || {
  dot::exit "Cannot checkout tpm repository"
}

dot::info "Installing tmux plugins …"

"${TPM_DIR}/bin/install_plugins"
