#!/usr/bin/env bash

# Helper function used to load additional dotfiles
load_dotfile() {
  # shellcheck source=/dev/null
  [ -r "$HOME/.dotfiles/$1" ] && source "$HOME/.dotfiles/$1"
}

# Helper function used to create a symbolic link
link_dotfile() {
  ln -fs "$HOME/.dotfiles/$1" "$HOME/$2"
}

# Ensure commonly used helper functions are available
load_dotfile "helpers/system"
load_dotfile "helpers/io"

# Display script information
e_header "Dotfiles – Setup Assistant"

# Ask before potentially overwriting dotfiles
seek_confirmation "Link dotfiles (this may overwrite existing files)?"

if is_confirmed; then

  # Copy '.gitconfig' if it does not exist
  [[ ! -f "$HOME/.gitconfig" ]] && cp "$HOME/.dotfiles/config/git/config" "$HOME/.gitconfig"

  # Create the necessary symbolic links between the `.dotfiles` and `HOME`
  # directory.
  link_dotfile "config/zshrc"           ".zshrc"
  link_dotfile "config/bashrc"          ".bashrc"
  link_dotfile "config/bashrc"          ".bash_profile"
  link_dotfile "config/inputrc"         ".inputrc"
  link_dotfile "config/vim"             ".vim"
  link_dotfile "config/vimrc"           ".vimrc"
  link_dotfile "config/gemrc"           ".gemrc"
  link_dotfile "config/tmux"            ".tmux.conf"
  link_dotfile "config/dircolors"       ".dircolors"
  link_dotfile "config/git/attributes"  ".gitattributes"
  link_dotfile "config/git/ignore"      ".gitignore"

fi

# Customize Mac OSX default settings
if is_mac; then

  seek_confirmation "Do you want to customize the OSX settings?"

  if is_confirmed; then
    load_dotfile "config/osx/config"
  fi

fi

# Install homebrew on Mac OSX
if is_mac && ! is_executable brew; then

  seek_confirmation "Install homebrew?"

  if is_confirmed; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    load_dotfile "config/osx/brew"
  fi

fi

# Install npm on Mac OSX
if is_mac && ! is_executable npm; then

  seek_confirmation "Install node package manager?"

  if is_confirmed; then
    mkdir "$HOME/.npm-packages"
    echo "prefix=$HOME/.npm-packages" >> ~/.npmrc
    echo "NPM_PACKAGES=\"\$HOME/.npm-packages\"" >> ~/.bash_user
    echo "NODE_PATH=\"\$NPM_PACKAGES/lib/node_modules:\$NODE_PATH\"" >> ~/.bash_user
    curl -L https://www.npmjs.com/install.sh | sh
  fi

fi

# Reload shell
e_success "Dotfiles setup successfully!"
exec "$SHELL" -l
