# misc/Brewfile

# (1) Repositories -------------------------------- {{{1

tap 'github/gh'
tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'


# (2) Formulae ------------------------------------ {{{1

brew 'zsh'
brew 'fzf'

brew 'rsync'
brew 'curl'
brew 'wget'
brew 'lftp'
brew 'jq'

brew 'git'
brew 'git-delta'
brew 'git-flow-avh'
brew 'gh'

brew 'ack'
brew 'tree'
brew 'bat'
brew 'fd'
brew 'ripgrep'

brew 'neovim'
brew 'shellcheck'
brew 'yamllint'
brew 'tidy-html5', args: ['HEAD']

brew 'tag'
brew 'trash'
brew 'tldr'


# (3) Applications -------------------------------- {{{1

cask 'appcleaner'

cask 'arc'
cask 'firefox'
cask 'google-chrome'

cask 'visual-studio-code'

cask 'font-charter'
cask 'font-fira-sans'
cask 'font-fira-code'
cask 'font-ibm-plex'


# vim:foldmethod=marker:foldlevel=2
