" nvimrc                                                                  ><>°
"
" -----------------------------------------------------------------------
" Table of Contents
" -----------------------------------------------------------------------
" 1. Path expansion
" 2. Python Setup
" 3. Vim Configuration
" -----------------------------------------------------------------------


" (1) Path expansion ---------------------------------------------------- {{{1

let g:vimrc_home = fnamemodify(resolve(expand('$MYVIMRC')), ':p:h')


" (1) Python Setup  ----------------------------------------------------- {{{1

let s:pyenv_python3 = expand('$PYENV_ROOT/versions/3.12.1/bin/python')

let s:python3 = '/usr/bin/python3'
let s:python2 = '/usr/bin/python2'

if executable(s:python2)
  let g:python2_host_prog = s:python2
else
  let g:loaded_python_provider = 0
endif

if executable(s:pyenv_python3)
  let g:python3_host_prog = s:pyenv_python3
elseif executable(s:python3)
  let g:python3_host_prog = s:python3
else
  let g:loaded_python3_provider = 0
endif


" (2) Vim Configuration ------------------------------------------------- {{{1

execute 'source ' . g:vimrc_home . '/vimrc'


" vim:foldmethod=marker:foldlevel=2
