" vimrc

if version >= 704                     " Ignore configuration on older systems

" -------------------------------------
" Table of Contents
" -------------------------------------
" 1. General Settings
" 2. Look & Feel
" 3. Text Editing and Searching
" 4. Indentation and Tabs
" 5. Vim Plugins
" -------------------------------------


" 1. General settings ----------------- {{{1

let g:vim_home_dir   = fnamemodify(resolve(expand('$MYVIMRC')), ':p:h')
let g:vim_plugin_dir = g:vim_home_dir . '/bundle'

set nocompatible                      " Break backwards compatibility with vi
set encoding=utf-8                    " Encoding used in vim
set ttyfast                           " Optimize for fast terminal connection
set lazyredraw                        " No redraw for macros and commands
set synmaxcol=512                     " Reduce number of columns to highlight
set hidden                            " Hide modified buffers, don't complaint
set autoread                          " Reload file if modified outside vim
set history=1000                      " Increase number of commands saved
set switchbuf+=useopen                " Reuse open buffers
set clipboard+=unnamed                " Use system clipboard by default
set fileformats=unix,dos,mac          " Enable automatic fileformat detection

set splitright                        " Split to the right
set splitbelow                        " Split to the bottom

set noswapfile                        " Do not create swap files for buffers
set undofile                          " Save undo history to file
set undolevels=500                    " Reduce number of changes saved

" a) Temporary Files ------------------ {{{2
exe 'set viminfo+=n' . g:vim_home_dir . '/tmp/viminfo'
exe 'set directory=' . g:vim_home_dir . '/tmp/swap//'
exe 'set undodir='   . g:vim_home_dir . '/tmp/undo//'
exe 'set backupdir=' . g:vim_home_dir . '/tmp/backup//'
" }}}


" 2. Look & Feel ---------------------- {{{1

if has('gui_running')

  "set guifont=Menlo\ Regular:h15      " Select font to use
  "set linespace=2                     " Increase spacing between lines

  set guifont=CamingoCode\ Regular:h16 " Prefer CamingoCode if available
  set guioptions-=m                    " Hide menubar
  set guioptions-=T                    " Hide toolbar

  set columns=180 lines=50             " Provide enough space for two panes

endif

colorscheme solarized                 " Select color theme to use

set title                             " Allow vim to customize the title
set number                            " Show line numbers
set cursorline                        " Highlight current line
set ruler                             " Display cursor position
set showcmd                           " Show currently running command
set noshowmode                        " Mode is displayed in lightline already
set shortmess=aoOtI                   " Use abbreviation in messages
set showmatch                         " Highlight matching parenthesis
set showbreak=↪                       " Show line breaks

set laststatus=2                      " Always display the status line
set cmdheight=1                       " Avoid hit-enter prompts
set pumheight=10                      " Limit visible entries of the popup menu

set list                              " Show invisible characters
set listchars=tab:→\                  " Show tab stops
set listchars+=trail:·                " Show trailing spaces
set listchars+=nbsp:⣿                 " Show non breaking spaces
set listchars+=extends:»              " Line continues off-screen
set listchars+=precedes:«             " Line precedes off-screen
"set listchars+=eol:¬                 " Show end of line markers

set mouse=a ttymouse=xterm2           " Enable mouse support. Shame on me...

set scrolloff=8                       " Min. lines to keep above/below
set sidescrolloff=16                  " Min. cols to keep left/right

set wildmenu                          " Visual autocomplete for command menu
set wildmode=list:longest             " Set wildmenu to list choice

set wildignore+=*/.git/*,*/.hg/*,*/.svn/*
set wildignore+=*.jpg,*.jpeg,*.png,*.gif,*.tiff,*.psd
set wildignore+=*.zip,*.tar,*.tar.gz,*.dmg
set wildignore+=*.pdf,*.doc,*.docx,*.xls,*.xlsx,*.ppt,*.pptx
set wildignore+=*.mp3,*.mp4,*.mov
set wildignore+=*.gem,gems/**
set wildignore+=*/node_modules/**
set wildignore+=*/tmp/**,.DS_Store,Icon


" 3. Text Editing and Searching ------- {{{1

set nostartofline                     " Do not reset cursor position
set backspace=2                       " Equivalent to backspace=indent,eol,start

set incsearch                         " Highlight dynamically while typing
set hlsearch                          " Highlight matches of previous search
set ignorecase                        " Ignore case when searching
set smartcase                         " Be case-sensitive when using capitals

set nowrap                            " No line wrapping by default
set textwidth=0                       " Avoid line breaks when pasting

set formatoptions-=o                  " Do not insert comment leader after o
set formatoptions+=n                  " Recognize numbered lists in comments
set formatoptions+=j                  " Remove comment leader when joining

set nrformats-=octal                  " Don't use octals when incrementing

set complete-=i                       " Don't scan included files
set complete-=t                       " Avoid tag completion
set completeopt-=preview              " Hide extra information in pum
set completeopt+=longest              " Only insert the longest common text
set completeopt+=menu                 " Show possible completions in a popup
set completeopt+=menuone              " Show the popup for a single match

set diffopt+=vertical                 " Start diff mode with vertical splits
set diffopt+=filler                   " Keep the windows synchronized
set diffopt+=iwhite                   " Ignore changes in amount of whitespace

set matchpairs+=<:>                   " Change html tags with ci< or ci>

set nospell                           " Disable spell checking by default
set spelllang=en_us,de_de             " Languages to use for spell checks

set foldcolumn=0                      " Do not show a fold column
set nofoldenable                      " Open all folds by default
set foldlevel=99
set foldlevelstart=99


" 4. Indentation and Tabs ------------- {{{1

set autoindent                        " Start indentation at same position
set smarttab                          " Insert blanks according to shiftwidth
set expandtab                         " Expand <Tab>s with spaces
set tabstop=2                         " Proper display of files with tabs
set shiftwidth=2                      " Spaces for each tab stop of (auto)indent
set softtabstop=2                     " Set virtual tab stop
set shiftround                        " Round indents to multiple of shiftwidth


" 5. Vim Plugins ---------------------- {{{1

call plug#begin(g:vim_plugin_dir)

  " a) Appearance --------------------- {{{2
  " ¹  Customize vim's statusline
  " ²  Show file changes in gutter
  " ³  Highlight colors in CSS/SASS
  " -----------------------------------
  Plug 'itchyny/lightline.vim'
  Plug 'airblade/vim-gitgutter'
  Plug 'ap/vim-css-color'

  " b) System Integration ------------- {{{2
  " ¹  Navigate files/buffers
  " ²  Open locally modified files
  " ³  Search file contents
  " ⁴  Simplified cut & paste
  " ⁵  Unix utilities in vim
  " ⁶  Git integration
  " ⁷  Look up documentation
  " -----------------------------------
  Plug 'ctrlpvim/ctrlp.vim'
  Plug 'jasoncodes/ctrlp-modified.vim'
  Plug 'mileszs/ack.vim'
  Plug 'svermeulen/vim-easyclip'
  Plug 'tpope/vim-eunuch'
  Plug 'tpope/vim-fugitive'
  Plug 'keith/investigate.vim'

  " c) Text Editing ------------------- {{{2
  " ¹  Check file syntax
  " ²  Snippet manager
  " ³  Wrap text objects
  " ⁴  Toggle comments
  " ⁵  Align text elements
  " ⁶  Remove trailing spaces
  " ⁷  Write html markup easily
  " -----------------------------------
  Plug 'scrooloose/syntastic'
  Plug 'SirVer/ultisnips'
  Plug 'tpope/vim-surround'
  Plug 'tpope/vim-unimpaired'
  Plug 'tpope/vim-commentary'
  Plug 'junegunn/vim-easy-align'
  Plug 'itspriddle/vim-stripper'
  Plug 'ciaranm/detectindent'
  Plug 'mattn/emmet-vim', { 'for': ['html', 'html.twig', 'php', 'css', 'scss', 'sass'] }

  " d) Text Writing ------------------- {{{2
  " ¹  Soft wrap, better undo...
  " ²  Distraction free writing
  " -----------------------------------
  Plug 'reedes/vim-pencil', { 'for': 'markdown' }
  Plug 'junegunn/goyo.vim', { 'on': 'Goyo' }

  " e) Completion --------------------- {{{2
  " ¹  Tab or Auto-Complete
  " ²  HTML5 & SVG omnicomplete
  " ³  PHP omnicomplete
  " -----------------------------------
  Plug 'ervandew/supertab'
  Plug 'othree/html5.vim',           { 'for': ['html', 'svg', 'php'] }
  Plug 'shawncplus/phpcomplete.vim', { 'for': 'php' }

  " f) Syntax/File Type Additions ----- {{{2
  " ¹  Support PHP 5.6 features
  " ²  Improve hilighting for Twig
  " ³  Add ES6 support
  " ⁴  Improve js indentation
  " ⁵  Improve higlighting for SASS
  " ⁶  Improve support for CSS3
  " ⁷  Load *.md files as markdown
  " ⁸  Update syntax and indentation
  " ⁹  Add Liquid & Jekyll support
  " ¹⁰ Highlighting & quote concealing
  " -----------------------------------
  Plug 'StanAngeloff/php.vim',      { 'for': 'php' }
  Plug 'evidens/vim-twig',          { 'for': 'html.twig' }
  Plug 'othree/yajs.vim',           { 'for': 'javascript' }
  Plug 'gavocanov/vim-js-indent',   { 'for': 'javascript' }
  Plug 'cakebaker/scss-syntax.vim', { 'for': 'scss' }
  Plug 'hail2u/vim-css3-syntax',    { 'for': ['css', 'scss'] }
  Plug 'tpope/vim-markdown',        { 'for': 'markdown' }
  Plug 'tpope/vim-git',             { 'for': ['git', 'gitcommit', 'gitconfig', 'gitrebase', 'gitsendmail'] }
  Plug 'tpope/vim-liquid',          { 'for': 'liquid' }
  Plug 'elzr/vim-json',             { 'for': 'json' }

  " g) Misc/Utility ------------------- {{{2
  " ¹  Auto-generate ctags
  " ²  Auto update working directory
  " ³  Support async commands
  " ⁴  Repeat plugin commands
  " ⁵  Fix cursor/focus events in tmux
  " -----------------------------------
  Plug 'ludovicchabant/vim-gutentags'
  Plug 'airblade/vim-rooter'
  Plug 'tpope/vim-dispatch'
  Plug 'tpope/vim-repeat'
  Plug 'sjl/vitality.vim'
  " }}}

call plug#end()

runtime! config/*.vim                 " Load additional config files
set secure                            " Block some write operations and autocmd


" }}}1

endif " version >= 700

" vim:foldmethod=marker:foldlevel=2
