#!/usr/bin/env bash

# Allow aliases to be used with sudo
alias sudo='sudo '

# Run the last command as root
alias plz='sudo !!'

# Directory navigation
alias ..='cd ..'
alias cd..='cd ..'

# Create or remove directory
alias md='mkdir -p'
alias rd='rmdir'

# Detect whether coreutils are installed on the current system
if type gls >/dev/null 2>&1; then
  lscmd='gls'
else
  lscmd='ls'
fi

# Detect which ls flavor is available
if $lscmd --color > /dev/null 2>&1; then
  lscolorflag='--color'
else
  lscolorflag='-G'
fi

# Create aliases to list directory contents
alias ll="${lscmd} -alhF ${lscolorflag}"
alias ls="command ${lscmd} ${lscolorflag}"

# Always enable colord `grep` output
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Intuitive map function e.g.: find . -name .gitattributes | map dirname
alias map="xargs -n1"

# Reload the shell (i.e. invoke as a login shell)
alias reload='exec $SHELL -l'

# Frequently used utilities
alias g='git'
alias e='$EDITOR'
alias v='atom'
alias rsyncp='rsync --archive --compress --verbose --progress --partial --human-readable --rsh ssh'
alias rsyncfat='rsync --recursive --links --devices --specials --size-only --no-times --no-perms --no-owner --no-group --verbose --progress --human-readable'

# Create aliases based on the current operating system
case "$OSTYPE" in
  darwin*) # Mac OSX
    alias finder='open -a Finder .'
    alias subl='open -a Sublime\ Text'
    alias chrome='open -a Google\ Chrome'
    alias firefox='open -a Firefox'
    alias safari='open -a Safari'
    alias vimr='open -a VimR'
    alias pubkey='more ~/.ssh/id_rsa.pub | pbcopy | printf "=> Public key copied.\n"'
    alias update='sudo softwareupdate -i -a; brew update; brew upgrade --all; brew cleanup; npm update npm -g; npm update -g; gem update --system; gem update'
    alias cleanup='find . -type f -name "*.DS_Store" -ls -delete'
    alias emptytrash='sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl'
  ;;
esac

# Clear local variables
unset lscmd lscolorflag
