#!/usr/bin/env bash

# Avoid loading dotfiles for non-interactive shells
[ -z "$PS1" ] && return

# Base folder containing all dotfiles
export DOTFILES_PATH=~/.dotfiles

# Load utility functions
source $DOTFILES_PATH/helpers/array

# Load common shell aliases
source $DOTFILES_PATH/config/aliases

# Customize the bash shell
source $DOTFILES_PATH/config/bash/options
source $DOTFILES_PATH/config/bash/prompt

# Load functions but ignore zsh functions
ignore=(async prompt_pure_setup)
for file in $DOTFILES_PATH/functions/*; do
    filename=$(basename "$file")
    array_contains "${ignore[@]}" "$filename"
    if [ $? -eq 1 ]; then
      source "$file"
    fi
done
