#!/usr/bin/env bash

#
# Extract various compression formats with a single function call
#
# Usage: extract file
#
# $1 = Path to the archive to extract.
#
extract () {
  if [ -f "$1" ]; then
    local err="$1 cannot be extracted via extract()";
    case "$1" in
      *.tar.bz2)  tar xjf "$1";;
      *.tar.gz)   tar xzf "$1";;
      *.gz)       gunzip "$1";;
      *.tar)      tar xf "$1";;
      *.tbz2)     tar xjf "$1";;
      *.tgz)      tar xzf "$1";;
      *.zip)      unzip "$1";;
      *.Z)        uncompress "$1";;
      *.rar)      type unrar >/dev/null 2>&1 && unrar x "$1" || echo "$err";;
      *)          echo "$err";;
    esac
  else
    echo "extract: $1: No such file or directory"
  fi
}
