#!/usr/bin/env bash

#
# Alias for tree. Display a colored list of all the contents of a
# given directory.
#
# Usage:  t [directory]
#
# [$1] = Path to the directory to display the contents of.
#
t() {
  tree -aC -I '.cache|.Trash|.git|node_modules' --dirsfirst "$@" | less -FRNX;
}
