#!/usr/bin/env bash

# Update homebrew
brew update
brew upgrade --all

# Install GNU core utilities
brew install coreutils

# Update shell
brew install zsh
brew install bash
brew install bash-completion2

# Update system utilities
brew install homebrew/dupes/grep
brew install homebrew/dupes/openssh
brew install homebrew/fuse/encfs

# Install terminal utilities
brew install tmux
brew install git
brew install git-flow
brew install wget
brew install tree
brew install rsync
brew install the_silver_searcher

# Development Tools
brew install vim
brew install ctags
brew install dnsmasq
brew install node --without-npm
brew install mysql
brew install homebrew/php/php56
brew install homebrew/php/php56-xdebug
brew install homebrew/php/php56-mcrypt
brew install homebrew/php/adminer
brew install homebrew/php/php-code-sniffer
brew install homebrew/php/phpmd
brew install homebrew/php/composer
brew install homebrew/php/drush
brew install homebrew/php/drupalconsole
brew install homebrew/php/wp-cli

# Remove outdated versions from cellar
brew cleanup
