#!/usr/bin/env bash
#
# @file Generate an index file of names found in source files

set -e

PATH="/usr/local/bin:${PATH}"
GIT_DIR="$(git rev-parse --git-dir)"

if ! command -v "ctags" >/dev/null 2>&1; then
  exit 1;
fi

trap 'rm -f "${GIT_DIR}/$$.tags"' EXIT

git ls-files | \
  ctags --tag-relative="always" -L - -f "${GIT_DIR}/$$.tags"

mv "${GIT_DIR}/$$.tags" "${GIT_DIR}/tags"

